apiVersion: core.openeverest.io/v1alpha1
kind: Plugin
metadata:
  name: {{ .Release.Name }}
spec:
  displayName: {{ .Values.plugin.displayName | quote }}
  description: {{ .Values.plugin.description | quote }}
  version: {{ .Chart.AppVersion | quote }}
  vendor: {{ .Values.plugin.vendor | quote }}
  enabled: {{ .Values.plugin.enabled }}
  icon: {{ .Values.plugin.icon | quote }}
  backend:
    serviceRef:
      namespace: {{ .Release.Namespace }}
      name: {{ include "plugin-mongodb-explorer.fullname" . }}
      port: {{ .Values.service.port }}
    modes:
      requestHandler:
        basePath: "/api"
  frontend:
    bundlePath: {{ .Values.plugin.bundlePath | quote }}
    extensionPoints:
      {{- toYaml .Values.plugin.extensionPoints | nindent 6 }}
  permissions:
    - verb: read
      resource: database-clusters
    - verb: read
      resource: database-cluster-connection-details
